/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteRouteImport } from './routes/_authenticated/transactions/route'
import { Route as AuthenticatedProductsRouteRouteImport } from './routes/_authenticated/products/route'
import { Route as AuthenticatedGcashRouteRouteImport } from './routes/_authenticated/gcash/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPosIndexRouteImport } from './routes/_authenticated/pos/index'
import { Route as AuthenticatedGcashIndexRouteImport } from './routes/_authenticated/gcash/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRouteRoute =
  AuthenticatedTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRouteRoute =
  AuthenticatedProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGcashRouteRoute = AuthenticatedGcashRouteRouteImport.update({
  id: '/gcash',
  path: '/gcash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsRouteRoute,
  } as any)
const AuthenticatedPosIndexRoute = AuthenticatedPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGcashIndexRoute = AuthenticatedGcashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGcashRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/gcash': typeof AuthenticatedGcashRouteRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRouteRouteWithChildren
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/gcash/': typeof AuthenticatedGcashIndexRoute
  '/pos/': typeof AuthenticatedPosIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/gcash': typeof AuthenticatedGcashIndexRoute
  '/pos': typeof AuthenticatedPosIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/gcash': typeof AuthenticatedGcashRouteRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRouteRouteWithChildren
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteRouteWithChildren
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/gcash/': typeof AuthenticatedGcashIndexRoute
  '/_authenticated/pos/': typeof AuthenticatedPosIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gcash'
    | '/products'
    | '/transactions'
    | '/customers/$customerId'
    | '/customers/'
    | '/dashboard/'
    | '/gcash/'
    | '/pos/'
    | '/products/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/$customerId'
    | '/customers'
    | '/dashboard'
    | '/gcash'
    | '/pos'
    | '/products'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/gcash'
    | '/_authenticated/products'
    | '/_authenticated/transactions'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/customers/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/gcash/'
    | '/_authenticated/pos/'
    | '/_authenticated/products/'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gcash': {
      id: '/_authenticated/gcash'
      path: '/gcash'
      fullPath: '/gcash'
      preLoaderRoute: typeof AuthenticatedGcashRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsRouteRoute
    }
    '/_authenticated/pos/': {
      id: '/_authenticated/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof AuthenticatedPosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gcash/': {
      id: '/_authenticated/gcash/'
      path: '/'
      fullPath: '/gcash/'
      preLoaderRoute: typeof AuthenticatedGcashIndexRouteImport
      parentRoute: typeof AuthenticatedGcashRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedGcashRouteRouteChildren {
  AuthenticatedGcashIndexRoute: typeof AuthenticatedGcashIndexRoute
}

const AuthenticatedGcashRouteRouteChildren: AuthenticatedGcashRouteRouteChildren =
  {
    AuthenticatedGcashIndexRoute: AuthenticatedGcashIndexRoute,
  }

const AuthenticatedGcashRouteRouteWithChildren =
  AuthenticatedGcashRouteRoute._addFileChildren(
    AuthenticatedGcashRouteRouteChildren,
  )

interface AuthenticatedProductsRouteRouteChildren {
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsRouteRouteChildren: AuthenticatedProductsRouteRouteChildren =
  {
    AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  }

const AuthenticatedProductsRouteRouteWithChildren =
  AuthenticatedProductsRouteRoute._addFileChildren(
    AuthenticatedProductsRouteRouteChildren,
  )

interface AuthenticatedTransactionsRouteRouteChildren {
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedTransactionsRouteRouteChildren: AuthenticatedTransactionsRouteRouteChildren =
  {
    AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  }

const AuthenticatedTransactionsRouteRouteWithChildren =
  AuthenticatedTransactionsRouteRoute._addFileChildren(
    AuthenticatedTransactionsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedGcashRouteRoute: typeof AuthenticatedGcashRouteRouteWithChildren
  AuthenticatedProductsRouteRoute: typeof AuthenticatedProductsRouteRouteWithChildren
  AuthenticatedTransactionsRouteRoute: typeof AuthenticatedTransactionsRouteRouteWithChildren
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedPosIndexRoute: typeof AuthenticatedPosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedGcashRouteRoute: AuthenticatedGcashRouteRouteWithChildren,
  AuthenticatedProductsRouteRoute: AuthenticatedProductsRouteRouteWithChildren,
  AuthenticatedTransactionsRouteRoute:
    AuthenticatedTransactionsRouteRouteWithChildren,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedPosIndexRoute: AuthenticatedPosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
